# Generated by Django 3.0.7 on 2020-10-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0008_auto_20200810_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('resume', models.FileField(upload_to='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(max_length=300)),
                ('institute', models.CharField(max_length=300)),
                ('department', models.CharField(max_length=300)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='jobsapp.Job')),
            ],
        ),
    ]
