# Generated by Django 3.0.7 on 2020-11-15 18:33

from django.db import migrations, models
import datetime
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_userdetials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetials',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='userdetials',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userdetials',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdetials',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='userdetials',
            name='lastname',
        ),
        migrations.AddField(
            model_name='userdetials',
            name='current_city',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='current_ctc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='current_designation',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='current_org',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='email',
            field=models.EmailField(default=f"{uuid.uuid4()}@gmail.com", error_messages={'unique': 'A user with that email already exists.'}, max_length=254),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='expected_ctc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='fullname',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='highest_qualification',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='ngo_experience_mos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='ngo_experience_yrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='notice_period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='relocate',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='skill_set',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='total_experience_mos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetials',
            name='total_experience_yrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdetials',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
