# Generated by Django 3.0.7 on 2020-11-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_auto_20201116_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetials',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userdetials',
            name='email',
            field=models.EmailField(default='null', error_messages={'unique': 'A user with that email already exists.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='userdetials',
            name='relocate',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='null', max_length=10),
        ),
    ]
