# Generated by Django 3.0.7 on 2020-11-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0011_auto_20201116_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetials',
            name='email',
            field=models.EmailField(default='null', error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True),
        ),
    ]
