# Generated by Django 3.0.7 on 2020-12-11 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_auto_20201116_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetials',
            name='phone_number',
            field=models.CharField(default=1234567899, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10 digit number', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
