# Generated by Django 3.0.7 on 2020-12-11 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_userdetials_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetials',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10 digit number', regex='^\\d{10}$')]),
        ),
    ]
