# Generated by Django 3.0.7 on 2020-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0014_auto_20201211_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[('1', 'Bangalore'), ('1', 'Bhubaneswar'), ('1', 'Delhi'), ('1', 'Kolkata'), ('1', 'Lucknow'), ('1', 'Mumbai'), ('1', 'Patna'), ('1', 'Pune'), ('1', 'Raipur')], default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='grade',
            field=models.CharField(choices=[('1', 'Chief Executive Officer'), ('2', 'A-1'), ('3', 'A-2'), ('4', 'A-3'), ('5', 'A-4'), ('6', 'A-5'), ('7', 'A-6'), ('8', 'A-7'), ('9', 'A-8'), ('10', 'A-9'), ('11', 'Consultant'), ('12', 'Internship'), ('13', 'Volunteer')], default='null', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='positions',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Consultancy'), ('4', 'Internship'), ('4', 'Volunteering Assignment')], max_length=10),
        ),
    ]
