# Generated by Django 3.0.7 on 2020-12-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_auto_20201212_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(choices=[('1', 'Bangalore'), ('2', 'Bhubaneswar'), ('3', 'Delhi'), ('4', 'Kolkata'), ('5', 'Lucknow'), ('6', 'Mumbai'), ('7', 'Patna'), ('8', 'Pune'), ('9', 'Raipur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Consultancy'), ('4', 'Internship'), ('5', 'Volunteering Assignment')], max_length=10),
        ),
    ]
